# Generated by Django 4.0.6 on 2022-08-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('money', models.IntegerField(default=0)),
                ('detail', models.CharField(max_length=200)),
                ('skill', models.CharField(max_length=200)),
            ],
        ),
    ]
