# Generated by Django 4.0.6 on 2022-08-13 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wanted', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='detail',
            new_name='c_detail',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='money',
            new_name='c_money',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='position',
            new_name='c_position',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='skill',
            new_name='c_skill',
        ),
    ]
