# Generated by Django 4.0.6 on 2022-08-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wanted', '0002_rename_detail_company_c_detail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='c_detail',
            new_name='detail',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='c_money',
            new_name='money',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='c_id',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='c_position',
            new_name='skill',
        ),
        migrations.RemoveField(
            model_name='company',
            name='c_skill',
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
