# Generated by Django 4.0.6 on 2022-08-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wanted', '0003_rename_c_detail_company_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
